name: Docker-Build-And-Push-Image
on: [push]

permissions:
  id-token: write   # Mandatory for the OIDC handshake
  contents: read

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Authenticate AWS CLI using OIDC
      - name: Authenticate AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ACTIONS_GITHUB_ROLE_ARN }}
          aws-region: eu-west-1

      # Log into ECR
      - name: ECR login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build image and push image to ECR
      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          #ECT Address
          tags: ${{ steps.login-ecr.outputs.registry }}/memos-ecs:latest
          # enable the caching - so we dont constantly build images and push to ECR regardless if there has been change or not
          cache-from: type=gha 
          cache-to: type=gha,mode=max